# Generated by Django 3.2.18 on 2024-03-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomNumber',
        ),
    ]
